services:
  mdbook-build:
    image: rescue-ui-mdbook:local
    build: .
    volumes:
      - .:/book
      - ../public:/public
    command:
      - build
      - /book
      - -d
      - /public/docs
    user: ${CURRENT_USER}
  mdbook-serve:
    image: rescue-ui-mdbook:local
    volumes:
      - .:/book:ro
      - ../public:/public:ro
    ports:
      - 3000:3000
    command:
      - serve
      - -n
      - 0.0.0.0
      - /book
      - -d
      - /tmp
    depends_on:
      mdbook-build:
        condition: service_completed_successfully

